
- name: test status
  command: mysql neutron -e 'select * from ratelimit;'
  ignore_errors: True
  register: result

- name: copy mysql  ratelimit.sql file
  template: src=ratelimit.sql dest=/root/ratelimit.sql
  when: result|failed

- name: import ratelimite.sql to mysql database
  command: mysql -e 'use neutron;source /root/ratelimit.sql;'
  when: result|failed

- name: clear neutron database ml2_gre_endpoints
  command: mysql -e 'use neutron;TRUNCATE TABLE ml2_gre_endpoints;'
  when: result|failed

- name: stop neutron dhcp and l3 service to pacemaker
  command: sudo {{ item }}
  with_items:
    - "crm resource stop p_neutron-dhcp-agent"
    - "crm resource stop p_neutron-l3-agent"
