---
# Handlers for neutron notifications

- name: test status to neutron in pacemaker
  shell: crm configure show  |grep -q p_neutron-l3-agent-after-clone_p_neutron-openvswitch-agent
  ignore_errors: True
  register: result

- name: remove openvswitch and stop openvswitch
  command: sudo {{ item }}
  with_items:
   - "crm configure delete p_neutron-l3-agent-with-clone_p_neutron-openvswitch-agent"
   - "crm configure delete p_neutron-l3-agent-after-clone_p_neutron-openvswitch-agent"
   - "crm configure delete p_neutron-dhcp-agent-with-clone_p_neutron-openvswitch-agent"
   - "crm configure delete p_neutron-dhcp-agent-after-clone_p_neutron-openvswitch-agent"
   - "crm resource stop clone_p_neutron-openvswitch-agent"
  when: result|success
