---

- name: neutron db config
  hosts: mysqldb
  roles:
    - ConfigNeutronDB

- name: config controller node
  hosts: controller
  roles:
    - ConfigVxlan


- name: config compute node
  hosts: compute
  roles:
    - compute

- name: openstack cluster end config
  hosts: mysqldb
  roles:
    - EndConfig
